### ISSUE TITLE
Hi, I have a data question

### ISSUE THREAD

**Issue by 1075793472** [SmritiChawla/Precily#1]
Hello, thank you very much for your excellent work, could you please provide the names of the cells and drugs in the test set in fig2a? Thank you.

**Comment by SmritiChawla** [comment]
Thank you so much for your appreciation. Please find attached two files corresponding to cell line names and drug names used in Fig2a. Thanks
[Uploading Fig2a_cell.csv…]()
[Uploading Fig2a_drug.csv…]()

**Comment by SmritiChawla** [comment]
Thank you so much for your appreciation. Please find attached files corresponding to the cell line and drug names respectively used in Fig2a. 
Thank you.
[Fig2a_cell.csv](https://github.com/SmritiChawla/Precily/files/9795258/Fig2a_cell.csv)
[Fig2a_drug.csv](https://github.com/SmritiChawla/Precily/files/9795259/Fig2a_drug.csv)
